[project]
name = "lab-2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ipython",
    "matplotlib",
    "nbconvert>=7.17.0",
    "notebook",
    "torch",
]
